<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i</name>
   <tag></tag>
   <elementGuidId>6080ec9b-b339-4778-8141-298919c6fa45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label > i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;keterangan2447112&quot;)/label[1]/i[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[1]/i[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6e95c749-9e72-4fee-8271-c07a88e5b750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan2447112&quot;)/label[1]/i[1]</value>
      <webElementGuid>f2059c00-2126-41bd-b985-10f39323a67c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keterangan2447112']/label/i</value>
      <webElementGuid>c5fef405-4b86-4dbc-92ac-acc0d5200682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>1707d24e-1ad3-405f-94b5-162c734d47a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
