<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Powered by Joget_formGridFrame_formgrid_attachment_3902565</name>
   <tag></tag>
   <elementGuidId>319b7dc3-3820-4ffe-b867-2a8a497fac5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='formGridFrame_formgrid_attachment_3902565']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@class = 'boxy-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formGridFrame_formgrid_attachment_3902565</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>771e908e-7208-4f51-a74d-07532b8de543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridFrame_formgrid_attachment_3902565</value>
      <webElementGuid>5054cebf-d80c-465c-a77d-f2b90d898b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formGridFrame_formgrid_attachment_3902565</value>
      <webElementGuid>cf05836a-4719-4070-b9b8-599d6640c2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/jw/images/v3/cj.gif</value>
      <webElementGuid>7b5602dd-5df2-4483-b1d5-1397cc1f57d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boxy-content</value>
      <webElementGuid>0b3c4e37-dbe0-450e-9e71-c33c82d51ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridFrame_formgrid_attachment_3902565&quot;)</value>
      <webElementGuid>73c272d8-e7a1-4e34-a61f-f67f993c394f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='formGridFrame_formgrid_attachment_3902565']</value>
      <webElementGuid>a3d152c3-461d-4cb5-b4c2-442a23af10a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ADA91BDBC0FB4B1EB45C57663232EE5A']/table/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>ca92c4b7-40a6-48b5-9f46-03b898da98c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1e477218-fcc8-4882-8802-e5a8f0100aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'formGridFrame_formgrid_attachment_3902565' and @name = 'formGridFrame_formgrid_attachment_3902565' and @src = '/jw/images/v3/cj.gif']</value>
      <webElementGuid>b71dd5c2-7f8d-470f-bab4-711f9cc41018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
