<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Powered by Joget_formGridFrame_formgrid_appr_4097277</name>
   <tag></tag>
   <elementGuidId>c6d439f8-b7f6-46dc-902e-2bf1c5127f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='formGridFrame_formgrid_appr_4097277']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@class = 'boxy-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formGridFrame_formgrid_appr_4097277</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f5a58eee-06c2-418e-a648-8017d7455ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridFrame_formgrid_appr_4097277</value>
      <webElementGuid>93d348e1-5952-46f2-b5a0-4ff5e2bad640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formGridFrame_formgrid_appr_4097277</value>
      <webElementGuid>7d5bc311-741a-499b-8710-60041c424c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/jw/images/v3/cj.gif</value>
      <webElementGuid>edaf11be-9218-4390-b9eb-bbdb6ce9b9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boxy-content</value>
      <webElementGuid>a10ee130-eecc-42ac-bdde-6b01f30a82a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridFrame_formgrid_appr_4097277&quot;)</value>
      <webElementGuid>48e6e356-c0e0-4848-97e7-a84a29a31f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='formGridFrame_formgrid_appr_4097277']</value>
      <webElementGuid>9c807066-f9ca-4c38-ab70-b44dc60369eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ADA91BDBC0FB4B1EB45C57663232EE5A']/table[2]/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>2740be3a-d041-4e80-8e6c-2ef6fbf24b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>86ea65a1-2d2f-402c-aa74-cb23ef14f9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'formGridFrame_formgrid_appr_4097277' and @name = 'formGridFrame_formgrid_appr_4097277' and @src = '/jw/images/v3/cj.gif']</value>
      <webElementGuid>cbb6346d-5922-4190-8c61-32f1bf964836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
