<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sf_data_sub_employee_empl_code</name>
   <tag></tag>
   <elementGuidId>a4b7ecaf-d2e7-4f3f-a937-e2db9ec8783b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sf_data_sub_employee_empl_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sf_data_sub_employee_empl_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbdeb7e3-d1ed-4f3f-a5f4-2df5fced6754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sf_data_sub_employee_empl_code</value>
      <webElementGuid>6fa6bd01-ed86-43ac-9e4d-c16c42af5919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sf_data_sub_employee_empl_code</value>
      <webElementGuid>8edd5262-0307-4f0e-97e0-1f4fa1c9f2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_2248307</value>
      <webElementGuid>c300afc4-7ec6-4a0e-a9cc-8ac33c01c46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c767cf3-0607-4577-b699-7a621921d5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sf_data_sub_employee_empl_code&quot;)</value>
      <webElementGuid>7ee090af-d677-4e81-843e-56653c5b7886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sf_data_sub_employee_empl_code']</value>
      <webElementGuid>fcf28068-90b8-4b6d-9800-3b9e2472ff2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sf_data_sub_employee_section1']/div[2]/div/input</value>
      <webElementGuid>a8f47dc1-f61e-4714-9cff-3fdf9c91f5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/input</value>
      <webElementGuid>4cb88e68-2c1b-4e3a-a243-53177cad523a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sf_data_sub_employee_empl_code' and @name = 'sf_data_sub_employee_empl_code' and @type = 'text']</value>
      <webElementGuid>65f0e6d1-b2eb-4dd4-84db-41dc20027590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
