<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__assignmentComplete</name>
   <tag></tag>
   <elementGuidId>83e4b8bd-3bf7-4fc2-9ad2-bfcf04e947ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assignmentComplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assignmentComplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a0e4c1-3770-4e49-a54e-d2c61bf88af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignmentComplete</value>
      <webElementGuid>641c3418-b59c-4934-bb5d-77330230f4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignmentComplete</value>
      <webElementGuid>5128dad0-3030-4563-8994-34168454c0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-button-input</value>
      <webElementGuid>6cf34e78-ea9b-4df3-b8e6-57d6e6cc84eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2d8a284d-09c7-4b83-b4e6-9d6ad3d066f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Load Form</value>
      <webElementGuid>7cb37c7d-91f4-4cfc-85d8-a43c58667095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignmentComplete&quot;)</value>
      <webElementGuid>7e6f86ea-c154-471b-8bb5-3eef6ff9a214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assignmentComplete']</value>
      <webElementGuid>17967562-ba9c-4ecf-97e3-140ff2fe1fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-actions']/div[2]/div/i/input</value>
      <webElementGuid>5120d1cb-32c5-4ade-ae8f-9032dba76fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/input</value>
      <webElementGuid>86354051-320f-44df-8d0b-2fac3c5ebf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'assignmentComplete' and @name = 'assignmentComplete' and @type = 'submit']</value>
      <webElementGuid>840046ee-bc94-41ca-929d-852383cb6a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
