<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NET RATE_userview-icon</name>
   <tag></tag>
   <elementGuidId>3fcac483-7977-44e5-8e91-3c74bbcac8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='apps']/li[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c6d1493-622e-423c-937d-3627b117cbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userview-icon</value>
      <webElementGuid>89b09045-bd00-4d4a-b29d-bb662c752ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apps&quot;)/li[5]/a[@class=&quot;app-link&quot;]/span[@class=&quot;userview-icon&quot;]</value>
      <webElementGuid>f8cea3a2-0228-4c45-9145-70d304aca45d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='apps']/li[5]/a/span</value>
      <webElementGuid>47dfad05-625a-4db8-8f1d-c8450fcf030e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[5]/a/span</value>
      <webElementGuid>d9ed9bac-58b1-4d85-bd98-2260ebf9bba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='apps']/li[4]/a/span</value>
      <webElementGuid>1c2c4710-c55c-487e-bee3-ef791240845a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[4]/a/span</value>
      <webElementGuid>5248d726-b564-4a4a-bb02-ee3ee4f6fb2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
